version: '3'

networks:
  issola-dev:

volumes:
  dev-db:

services:
  dev-db:
    image: 'postgres:9.6'
    env_file: .env.development
    networks:
      - issola-dev
    ports:
      - 35432:5432
    volumes:
      - dev-db:/var/lib/postgresql/data
